version: "3"

networks:
  loki:

services:
  loki:
    image: grafana/loki:2.3.0
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}"
    ports:
      - "3100:3100"
    volumes:
      - ./loki_config.yml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki

  promtail:
    image: grafana/promtail:2.3.0
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}"
    ports:
      - "9080:9080"
    volumes:
      - ./promtail_config.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - loki

  grafana:
    image: grafana/grafana:latest
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}"
    ports:
      - "3000:3000"
    networks:
      - loki

  webapp:
    image: annastrcv/msc_time:latest
    logging:
      driver: "json-file"
      options:
        tag: "{{.ImageName}}|{{.Name}}"
    ports:
      - "5000:5000"
    networks:
      - loki
