global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: web
    static_configs:
      - targets: ['host.docker.internal:5000']
  - job_name: prometheus
    static_configs:
      - targets: ['host.docker.internal:9090']
  - job_name: loki
    static_configs:
      - targets: ['loki:3100']