pipeline {
    agent {
        dockerfile true 
    }
 options {
   skipStagesAfterUnstable
    stages {
        stage('Build') {
            steps {
                echo "Build Stage"
            }
        }
    }
}
